user = {
    'fname': '',
    'lname': '',
    'facility': '',
    'role': '',
    'telephone': '',
    'mail': '',
    'uid': 'it.',
    'it_mail': '',
    'passwd': '',
    'objectID': '',
    'principalName': '',
    'empfang': 2,
    'kundenservice': '',
    'it_support': '',
    'grafikdesign': '',
    'diversity': '',
    'finanzanalyse': '',
    'dig_arbeitsplatz': '',
    'it_administration': '',
    'projektmanagement': '',
    'dig_marketing': '',
    'mc_adf': '',
    'vertrieb_verkauf': '',
    'mc_af': '',
    'soft_skills': '',
    'jobcoaching': '',
    'mc_aaf': '',
    'softwareentwicklung': '',
    'datenanalyse': '',
    'dynamics365': '',
    'microsoft365': '',
    'power_platform': '',
    'teams': '',
    'search': '',
    'tmp_passwd': '',
    'Netzwerke nutzen': '',
    'Bewerbung optimieren': '',
    'Kommunizieren via E-Mail': '',
    'Jobsuche perfektionieren': '',
    'Selbstmanagement lernen': '',
    'Kollaboration über Teams': '',
    'license': 2,
}

behavior_control = {
    'read_from_list': False,
    'headless_browser': True
}
